<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('roles')->insert(array(
            array(
                'id'    => '1',
                'name' => 'admin',
                'label' => 'Admin',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id'    => '2',
                'name' => 'support',
                'label' => 'Support',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id'    => '3',
                'name' => 'driver',
                'label' => 'Driver Account',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id'    => '4',
                'name' => 'restaurant',
                'label' => 'Restaurant Account',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id'    => '5',
                'name' => '',
                'label' => 'Customer Account',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id'    => '6',
                'name' => 'finance_officer',
                'label' => 'Finance Officer',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
            array(
                'id'    => '7',
                'name' => 'finance_manager',
                'label' => 'Finance Manager',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ),
        ));

        DB::table('users')->insert([
             array('id' => '1','name' => 'Admin','email' => 'admin@pomtech.com','email_verified_at' => NULL,'phone' => NULL,'firebase_token' => NULL,'password' => '$2y$10$jSdbKJogp3Zi23GCych3xuw6SNGHigySZr8Pix.Y3d4.kWvzH1/wy','status' => '1','role_id' => '1','remember_token' => NULL,'created_at' => '2021-05-04 15:01:03','updated_at' => '2021-05-04 15:01:03'),
              array('id' => '2','name' => 'Support','email' => 'support@pomtech.com','email_verified_at' => NULL,'phone' => NULL,'firebase_token' => NULL,'password' => '$2y$10$MLDhAVrPo3Vy1sF.ISZ/AOh03lIGFdLQnk/qM6KLz0oK3ovhFoLqy','status' => '1','role_id' => '2','remember_token' => NULL,'created_at' => '2021-05-04 15:01:03','updated_at' => '2021-05-04 15:01:03'),
              array('id' => '3','name' => 'Driver','email' => 'driver@pomtech.com','email_verified_at' => NULL,'phone' => NULL,'firebase_token' => NULL,'password' => '$2y$10$Q7rClUqZ6H.yzwRwaJnea.XWO5ewK6XFPw.6gvzIUt4gdvs7BOzTC','status' => '1','role_id' => '3','remember_token' => NULL,'created_at' => '2021-05-04 15:01:03','updated_at' => '2021-05-04 15:01:03'),
              array('id' => '4','name' => 'Fifty-Fifty','email' => '5050@pomtech.com','email_verified_at' => NULL,'phone' => NULL,'firebase_token' => NULL,'password' => '$2y$10$Q8Jc6gI.nPLP52xNGtOC3ewpgjO3kjm0vS0kCJ94Sg7O9Fzsx.VFi','status' => '1','role_id' => '4','remember_token' => NULL,'created_at' => '2021-05-04 15:01:03','updated_at' => '2021-05-04 15:01:03'),
              array('id' => '5','name' => 'Herat Super Market','email' => 'herat@pomtech.com','email_verified_at' => NULL,'phone' => NULL,'firebase_token' => NULL,'password' => '$2y$10$kXAPwxiVLhvkqeGkTrLA/OW9EZQ40GLM7UuMlsqXRwvpIPnHtLG6K','status' => '1','role_id' => '4','remember_token' => NULL,'created_at' => '2021-05-04 15:01:03','updated_at' => '2021-05-04 15:01:03'),
              array('id' => '6','name' => 'Paik Motor1','email' => 'paik@pomtech.com','email_verified_at' => NULL,'phone' => NULL,'firebase_token' => NULL,'password' => '$2y$10$XLFfnypodNbzDDHpQyitRuDCYBAEIprv2GWRT6zV4ihe7ZgUSv0DW','status' => '1','role_id' => '3','remember_token' => NULL,'created_at' => '2021-05-04 15:01:03','updated_at' => '2021-05-04 15:01:03'),
              array('id' => '7','name' => 'Abbas Jafari','email' => '2021-05-05 10:25:21@customer.com','email_verified_at' => NULL,'phone' => '0787072236','firebase_token' => 'RRNkiQ5bo6Sxdv8NDMggeV5LyIm2','password' => '$2y$10$avS8YNeGtygEGelXww6yxOYZaE4Opkh2ouhILFGzqIQGYyAOaSFYW','status' => '1','role_id' => '5','remember_token' => NULL,'created_at' => '2021-05-05 10:25:21','updated_at' => '2021-05-05 10:25:21'),
              array('id' => '8','name' => 'Ghulam Bargar','email' => 'g.long@bargar.com','email_verified_at' => NULL,'phone' => NULL,'firebase_token' => NULL,'password' => '$2y$10$UojEHfw4dDaxM/vKvR60ruM7yPOED39ikd19/wXoaj8Ls4ioRtg3W','status' => '1','role_id' => '4','remember_token' => NULL,'created_at' => '2021-05-04 15:01:03','updated_at' => '2021-05-04 15:01:03'),
              array('id' => '9','name' => 'Ahmad Zia','email' => 'zia@pomtech.com','email_verified_at' => NULL,'phone' => NULL,'firebase_token' => NULL,'password' => '$2y$10$DfAxrS4ZMYQYzW2RL3JxKOVpP4gvj4jFFf0slGYVyaPY4DxuBSC/m','status' => '1','role_id' => '6','remember_token' => NULL,'created_at' => '2021-05-04 15:01:03','updated_at' => '2021-05-04 15:01:03'),
              array('id' => '10','name' => 'Karima Salehi','email' => 'salehi@pomtech.com','email_verified_at' => NULL,'phone' => NULL,'firebase_token' => NULL,'password' => '$2y$10$Ex5tv1aHgTKVb/F0g4kyvuLUeXlATpdVsjcyNAoqLzAqXKWaFz7yK','status' => '1','role_id' => '7','remember_token' => NULL,'created_at' => '2021-05-04 15:01:03','updated_at' => '2021-05-04 15:01:03'),
              array('id' => '26','name' => 'Ehsan Sultanzadeh','email' => '2021-05-05 10:37:47@customer.com','email_verified_at' => NULL,'phone' => '0700474747','firebase_token' => 'e3AvrfjyfZf3OCl1UlTuBEoV0D03','password' => '$2y$10$sovPVTHk5gU095uBWamyrO4sd/R90OPcT0WC2lZ99Hh5WwdPfTIOK','status' => '1','role_id' => '5','remember_token' => NULL,'created_at' => '2021-05-05 10:37:47','updated_at' => '2021-05-05 10:37:47')
        ]);

        DB::table('commissions')->insert([
            array('id' => '1','created_at' => '2021-03-01 04:54:30','updated_at' => '2021-03-01 04:54:30','type' => 'general','value' => NULL,'percentage' => '10','status' => '1','title' => 'General commisssion 10%'),
            array('id' => '2','created_at' => '2021-03-01 04:54:56','updated_at' => '2021-03-01 04:54:56','type' => 'delivery','value' => NULL,'percentage' => '5','status' => '1','title' => 'Delivery 5%')
        ]);

        DB::table('branches')->insert(array(
            array('id' => '1','created_at' => NULL,'updated_at' => NULL,'user_id' => '4','business_type' => 'food','main_commission_id' => '1','deliver_commission_id' => '2','status' => '1'),
            array('id' => '2','created_at' => NULL,'updated_at' => NULL,'user_id' => '5','business_type' => 'food','main_commission_id' => '1','deliver_commission_id' => NULL,'status' => '1'),
            array('id' => '3','created_at' => NULL,'updated_at' => NULL,'user_id' => '8','business_type' => 'food','main_commission_id' => '1','deliver_commission_id' => NULL,'status' => '1')
        ));

        DB::table('branche_main_info')->insert(array(
            array('id' => '1','created_at' => NULL,'updated_at' => NULL,'business_id' => '1','title' => 'Fifty-Fifty','description' => 'Eat anything with 50 Afs.','logo' => 'test_1614666474.png','banner' => 'deafult_banner.jpg','contact' => '+937909090','location' => 'Herat-Chawk Golha','note' => NULL,'status' => 'old'),
              array('id' => '2','created_at' => NULL,'updated_at' => NULL,'business_id' => '2','title' => 'Herat Super Market','description' => 'Any you need, we have.','logo' => 'logo_1614666570.png','banner' => 'deafult_banner.jpg','contact' => '+937303030','location' => 'Herat-Chawk Shahre Now','note' => NULL,'status' => 'old'),
              array('id' => '3','created_at' => NULL,'updated_at' => NULL,'business_id' => '3','title' => 'Ghulam Bargar','description' => 'Any you need, we have.','logo' => 'logo_1614666570.png','banner' => 'deafult_banner.jpg','contact' => '+937303030','location' => 'Herat-Chawk Shahre Now','note' => NULL,'status' => 'old'),
              array('id' => '4','created_at' => NULL,'updated_at' => '2021-03-24 16:05:20','business_id' => '1','title' => 'Fifty-Fifty','description' => 'Eat anything with 50 Afs. and 100','logo' => 'test_1614666474.png','banner' => 'deafult_banner.jpg','contact' => '+937909090','location' => 'Herat-Chawk Golha','note' => NULL,'status' => 'old'),
              array('id' => '5','created_at' => NULL,'updated_at' => '2021-03-25 12:15:55','business_id' => '2','title' => 'Herat Super Market','description' => 'Any you need, we have.','logo' => 'grocery-store_1616657916.jpg','banner' => 'deafult_banner.jpg','contact' => '+937303030','location' => 'Herat-Chawk Shahre Now','note' => NULL,'status' => 'approved'),
              array('id' => '6','created_at' => NULL,'updated_at' => NULL,'business_id' => '1','title' => 'Fifty-Fifty','description' => 'Eat anything with 50 Afs.','logo' => 'stick_1620192811.jpg','banner' => 'stick_1620192811.jpg','contact' => '+937909090','location' => 'Herat-Chawk Golha','note' => NULL,'status' => 'approved'),
              array('id' => '7','created_at' => NULL,'updated_at' => NULL,'business_id' => '3','title' => 'Ghulam Bargar','description' => 'Any you need, we have.','logo' => 'images_1620192835.jpg','banner' => 'images_1620192835.jpg','contact' => '+937303030','location' => 'Herat-Chawk Shahre Now','note' => NULL,'status' => 'approved')
        ));

          DB::table('items')->insert(array(
            array('id' => '1','created_at' => NULL,'updated_at' => NULL,'branch_id' => '1','category_id' => '1','status' => '1'),
            array('id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => '1','category_id' => '1','status' => '1'),
            array('id' => '3','created_at' => NULL,'updated_at' => NULL,'branch_id' => '2','category_id' => '2','status' => '1'),
            array('id' => '4','created_at' => NULL,'updated_at' => NULL,'branch_id' => '2','category_id' => '2','status' => '1'),
            array('id' => '5','created_at' => NULL,'updated_at' => NULL,'branch_id' => '3','category_id' => '2','status' => '1'),
            array('id' => '6','created_at' => NULL,'updated_at' => NULL,'branch_id' => '3','category_id' => '2','status' => '1'),
            array('id' => '7','created_at' => NULL,'updated_at' => NULL,'branch_id' => '1','category_id' => '1','status' => '1'),
            array('id' => '8','created_at' => NULL,'updated_at' => NULL,'branch_id' => '1','category_id' => '1','status' => '1'),
            array('id' => '9','created_at' => NULL,'updated_at' => NULL,'branch_id' => '2','category_id' => '1','status' => '1'),
            array('id' => '10','created_at' => NULL,'updated_at' => NULL,'branch_id' => '2','category_id' => '1','status' => '1'),
            array('id' => '11','created_at' => NULL,'updated_at' => NULL,'branch_id' => '2','category_id' => '1','status' => '1'),
            array('id' => '12','created_at' => NULL,'updated_at' => NULL,'branch_id' => '1','category_id' => '2','status' => '1'),
            array('id' => '13','created_at' => NULL,'updated_at' => NULL,'branch_id' => '1','category_id' => '1','status' => '1'),
            array('id' => '14','created_at' => NULL,'updated_at' => NULL,'branch_id' => '1','category_id' => '1','status' => '1'),
            array('id' => '15','created_at' => NULL,'updated_at' => NULL,'branch_id' => '1','category_id' => '1','status' => '1'),
            array('id' => '16','created_at' => NULL,'updated_at' => NULL,'branch_id' => '1','category_id' => '1','status' => '1'),
            array('id' => '17','created_at' => NULL,'updated_at' => NULL,'branch_id' => '1','category_id' => '1','status' => '1'),
            array('id' => '18','created_at' => NULL,'updated_at' => NULL,'branch_id' => '1','category_id' => '1','status' => '1')

          ));


        DB::table('item_details')->insert(array(
            array('id' => '1','created_at' => NULL,'updated_at' => NULL,'item_id' => '1','title' => 'Pizza','description' => 'پیتزا مخصوص با سوس','thumbnail' => 'noimage.jpg','price' => '50','package_price' => '0','unit' => 'piece','notes' => NULL,'details_status' => 'old'),
          array('id' => '2','created_at' => NULL,'updated_at' => NULL,'item_id' => '2','title' => 'همبرگر','description' => 'همبرگر با نون اضافی','thumbnail' => 'noimage.jpg','price' => '70','package_price' => '10','unit' => 'piece','notes' => NULL,'details_status' => 'old'),
          array('id' => '3','created_at' => NULL,'updated_at' => NULL,'item_id' => '3','title' => 'روغن','description' => '1 کیلو','thumbnail' => 'noimage.jpg','price' => '120','package_price' => '0','unit' => 'bottle','notes' => NULL,'details_status' => 'old'),
          array('id' => '4','created_at' => NULL,'updated_at' => NULL,'item_id' => '4','title' => 'کچالو','description' => 'کچالوی غزنی','thumbnail' => 'noimage.jpg','price' => '25','package_price' => '0','unit' => 'کیلو','notes' => NULL,'details_status' => 'old'),
          array('id' => '5','created_at' => NULL,'updated_at' => NULL,'item_id' => '5','title' => 'شوربا','description' => 'کچالوی غزنی','thumbnail' => 'noimage.jpg','price' => '25','package_price' => '0','unit' => 'کیلو','notes' => NULL,'details_status' => 'old'),
          array('id' => '6','created_at' => NULL,'updated_at' => NULL,'item_id' => '6','title' => 'دیزی','description' => 'کچالوی غزنی','thumbnail' => 'noimage.jpg','price' => '25','package_price' => '0','unit' => 'کیلو','notes' => NULL,'details_status' => 'old'),
          array('id' => '7','created_at' => NULL,'updated_at' => '2021-03-24 15:47:18','item_id' => '1','title' => 'Pizza 2','description' => 'پیتزا مخصوص با سوس','thumbnail' => 'noimage.jpg','price' => '50','package_price' => '0','unit' => 'piece','notes' => NULL,'details_status' => 'old'),
          array('id' => '8','created_at' => NULL,'updated_at' => NULL,'item_id' => '7','title' => 'چای','description' => NULL,'thumbnail' => 'noimage.jpg','price' => '120','package_price' => NULL,'unit' => NULL,'notes' => NULL,'details_status' => 'old'),
          array('id' => '9','created_at' => NULL,'updated_at' => '2021-03-24 16:05:07','item_id' => '7','title' => 'چای ۱','description' => NULL,'thumbnail' => 'noimage.jpg','price' => '120','package_price' => NULL,'unit' => NULL,'notes' => NULL,'details_status' => 'old'),
          array('id' => '10','created_at' => NULL,'updated_at' => '2021-03-25 09:39:36','item_id' => '8','title' => 'همبرگر 4','description' => 'asdfasdf','thumbnail' => 'noimage.jpg','price' => '47','package_price' => NULL,'unit' => 'piece','notes' => NULL,'details_status' => 'old'),
          array('id' => '11','created_at' => NULL,'updated_at' => '2021-03-25 12:03:45','item_id' => '1','title' => 'چپس ساده','description' => 'پیتزا مخصوص با سوس','thumbnail' => 'chips1_1616657218.jpg','price' => '50','package_price' => '0','unit' => 'piece','notes' => NULL,'details_status' => 'approved'),
          array('id' => '12','created_at' => NULL,'updated_at' => '2021-03-25 12:03:47','item_id' => '2','title' => 'همبرگر نونی','description' => 'همبرگر با نون اضافی','thumbnail' => 'bargar_1616657483.jpg','price' => '80','package_price' => '10','unit' => 'piece','notes' => NULL,'details_status' => 'approved'),
          array('id' => '13','created_at' => NULL,'updated_at' => '2021-03-25 12:03:48','item_id' => '7','title' => 'چپس مخصوص','description' => NULL,'thumbnail' => 'chips_1616657523.jpg','price' => '75','package_price' => NULL,'unit' => NULL,'notes' => NULL,'details_status' => 'approved'),
          array('id' => '14','created_at' => NULL,'updated_at' => '2021-03-25 12:03:50','item_id' => '8','title' => 'سمبوسه','description' => 'همراه با چپس','thumbnail' => 'content9555_1616657586.jpg','price' => '120','package_price' => NULL,'unit' => 'piece','notes' => NULL,'details_status' => 'approved'),
          array('id' => '15','created_at' => NULL,'updated_at' => '2021-03-25 12:16:03','item_id' => '3','title' => 'روغن','description' => '1 کیلو','thumbnail' => 'oil_1616657704.jpg','price' => '120','package_price' => '0','unit' => 'bottle','notes' => NULL,'details_status' => 'approved'),
          array('id' => '16','created_at' => NULL,'updated_at' => NULL,'item_id' => '4','title' => 'برنج','description' => '20 کیلو','thumbnail' => 'rice_1616657750.jpg','price' => '25','package_price' => '0','unit' => 'بوجی','notes' => NULL,'details_status' => 'old'),
          array('id' => '17','created_at' => NULL,'updated_at' => '2021-03-25 12:16:07','item_id' => '9','title' => 'آیسکریم','description' => '300 گرم','thumbnail' => 'cream_1616657797.jpg','price' => '60','package_price' => NULL,'unit' => 'عدد','notes' => NULL,'details_status' => 'approved'),
          array('id' => '18','created_at' => NULL,'updated_at' => '2021-03-25 12:16:05','item_id' => '4','title' => 'برنج','description' => '20 کیلو','thumbnail' => 'rice_1616657750.jpg','price' => '1200','package_price' => '0','unit' => 'بوجی','notes' => NULL,'details_status' => 'approved'),
          array('id' => '19','created_at' => NULL,'updated_at' => '2021-03-25 12:16:09','item_id' => '10','title' => 'روغن گیاهی','description' => 'آفتاب گردان','thumbnail' => 'oil2_1616657874.jpg','price' => '140','package_price' => NULL,'unit' => 'بوتل','notes' => NULL,'details_status' => 'approved'),
          array('id' => '20','created_at' => NULL,'updated_at' => '2021-03-25 12:19:46','item_id' => '5','title' => 'کیک','description' => 'کیک نانپزی','thumbnail' => 'image_1616658523.jpg','price' => '40','package_price' => '0','unit' => 'piece','notes' => NULL,'details_status' => 'approved'),
          array('id' => '21','created_at' => NULL,'updated_at' => '2021-03-25 12:19:48','item_id' => '6','title' => 'پیزا مخصوص','description' => NULL,'thumbnail' => 'images_1616658572.jpg','price' => '80','package_price' => '0','unit' => 'piece','notes' => NULL,'details_status' => 'approved'),
          array('id' => '22','created_at' => NULL,'updated_at' => '2021-03-25 12:29:06','item_id' => '11','title' => 'صابون','description' => 'گلنار','thumbnail' => '-زرد._1616659021.jpg','price' => '15','package_price' => NULL,'unit' => 'piece','notes' => NULL,'details_status' => 'approved'),
          array('id' => '23','created_at' => NULL,'updated_at' => '2021-03-25 12:16:07','item_id' => '12','title' => 'آیسکریم','description' => '300 گرم','thumbnail' => 'cream_1616657797.jpg','price' => '60','package_price' => NULL,'unit' => 'عدد','notes' => NULL,'details_status' => 'approved'),
          array('id' => '24','created_at' => NULL,'updated_at' => NULL,'item_id' => '13','title' => 'چپس ساده نونی','description' => 'جزئیات کلی','thumbnail' => 'chips_1619419645.jpg','price' => '40','package_price' => NULL,'unit' => NULL,'notes' => NULL,'details_status' => 'approved'),
          array('id' => '25','created_at' => NULL,'updated_at' => NULL,'item_id' => '14','title' => 'چپس ساده حلوایی','description' => 'جزئیات کلی','thumbnail' => 'content9555_1619419692.jpg','price' => '45','package_price' => NULL,'unit' => NULL,'notes' => NULL,'details_status' => 'approved'),
          array('id' => '26','created_at' => NULL,'updated_at' => NULL,'item_id' => '15','title' => 'چپس ساده خرمایی','description' => 'جزئیات کلی','thumbnail' => 'fast-food_1619419742.jpg','price' => '48','package_price' => NULL,'unit' => NULL,'notes' => NULL,'details_status' => 'approved'),
          array('id' => '27','created_at' => NULL,'updated_at' => NULL,'item_id' => '16','title' => 'چپس ساده مرغ','description' => 'جزئیات کلی','thumbnail' => 'stick2_1619419778.jpg','price' => '48','package_price' => NULL,'unit' => NULL,'notes' => NULL,'details_status' => 'approved'),
          array('id' => '28','created_at' => NULL,'updated_at' => NULL,'item_id' => '17','title' => 'چپس ساده ماهی','description' => 'جزئیات کلی','thumbnail' => 'food_1619419805.jpg','price' => '48','package_price' => NULL,'unit' => NULL,'notes' => NULL,'details_status' => 'approved'),
          array('id' => '29','created_at' => NULL,'updated_at' => NULL,'item_id' => '18','title' => 'چپس ساده تخم مرغ','description' => 'جزئیات کلی','thumbnail' => 'image_1619419828.jpg','price' => '48','package_price' => NULL,'unit' => NULL,'notes' => NULL,'details_status' => 'approved')
        ));

        DB::table('categories')->insert(array(
              array('id' => '1','created_at' => '2021-03-01 10:40:55','updated_at' => '2021-04-22 10:46:55','title' => 'پیتزا','type' => 'main_food','description' => 'داغ و گرم','thumbnail' => 'images_1619072215.jpg','status' => '1'),
              array('id' => '2','created_at' => '2021-03-01 10:41:06','updated_at' => '2021-04-22 10:47:05','title' => 'آیسکریم','type' => 'dessert','description' => 'یخ و خوشمزه','thumbnail' => 'Example01_1619072157.png','status' => '1'),
              array('id' => '3','created_at' => '2021-03-01 10:40:55','updated_at' => '2021-04-22 10:46:55','title' => 'برنج','type' => 'main_food','description' => 'داغ و گرم','thumbnail' => 'rice.jpg','status' => '1'),
              array('id' => '4','created_at' => '2021-03-01 10:41:06','updated_at' => '2021-04-22 10:47:05','title' => 'بستنی','type' => 'dessert','description' => 'یخ و خوشمزه','thumbnail' => 'Example03.png','status' => '1'),
              array('id' => '5','created_at' => '2021-03-01 10:40:55','updated_at' => '2021-04-22 10:46:55','title' => 'گوشت','type' => 'main_food','description' => 'داغ و گرم','thumbnail' => 'photo-1432139555190-58524dae6a55.jpg','status' => '1'),
              array('id' => '6','created_at' => '2021-03-01 10:41:06','updated_at' => '2021-04-22 10:47:05','title' => 'آجیل','type' => 'dessert','description' => 'یخ و خوشمزه','thumbnail' => 'Example04.png','status' => '1'),
              array('id' => '7','created_at' => '2021-03-01 10:40:55','updated_at' => '2021-04-22 10:46:55','title' => 'ایرانی','type' => 'main_food','description' => 'داغ و گرم','thumbnail' => 'photo-1455619452474-d2be8b1e70cd.jpg','status' => '1'),
              array('id' => '8','created_at' => '2021-03-01 10:41:06','updated_at' => '2021-04-22 10:47:05','title' => 'قهوه','type' => 'dessert','description' => 'یخ و خوشمزه','thumbnail' => 'Example02.png','status' => '1')
          ));

        DB::table('menus')->insert(array(
            array('id' => '1','created_at' => '2021-03-01 10:44:29','updated_at' => '2021-03-01 10:44:29','title' => 'سنی مخصوص','branch_id' => '3','status' => '1','items' => '["5", "6"]')
        ));

        DB::table('orders')->insert(array(
array('id' => '1','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '2','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '3','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '3','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '2','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '4','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '5','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '2','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '6','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '7','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '8','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '9','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '10','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '11','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '3','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '12','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '3','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '13','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '3','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '14','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '2','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '15','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '3','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '16','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '3','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '17','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '18','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '3','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '19','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '2','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '20','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '3','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '21','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '3','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '22','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '23','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '3','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '24','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '2','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '25','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '26','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '2','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '27','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '3','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '28','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '2','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '29','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '2','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '30','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '31','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '32','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '2','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '33','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '3','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '34','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '2','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '35','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '3','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'pending','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '36','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '2','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'reject','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '37','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '3','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'reject','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '38','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '3','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'reject','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '39','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '2','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'reject','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '40','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '3','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'reject','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '41','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'reject','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '42','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '2','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'reject','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '43','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'reject','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '44','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'reject','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '45','created_at' => Carbon::now()->subMinutes(rand(10, 90)),'updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'reject','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '46','created_at' => '2021-04-28 00:00:00','updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'completed','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '47','created_at' => '2021-04-25 00:00:00','updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'completed','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '48','created_at' => '2021-04-28 00:00:00','updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '3','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'completed','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '49','created_at' => '2021-04-28 00:00:00','updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'completed','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '50','created_at' => '2021-04-30 00:00:00','updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '2','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'completed','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '51','created_at' => '2021-04-28 00:00:00','updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '2','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'completed','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '52','created_at' => '2021-04-27 00:00:00','updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '2','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'completed','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '53','created_at' => '2021-04-28 00:00:00','updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'completed','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '54','created_at' => '2021-04-29 00:00:00','updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '1','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'completed','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0'),
  array('id' => '55','created_at' => '2021-04-27 00:00:00','updated_at' => NULL,'deleted_at' => NULL,'title' => NULL,'branch_id' => '2','customer_id' => '26','payment_id' => NULL,'has_delivery' => '1','total' => '355','commission_value' => '15','status' => 'completed','note' => '\'\'','reciever_phone' => '\'0790909090\'','contents' => '{"contents": [{"item_1": {"count": "2", "price": "100", "item_id": "1"}}, {"item_2": {"count": "4", "price": "100", "item_id": "2"}}, {"item_3": {"count": "8", "price": "200", "item_id": "5"}}]}','paid' => '0')

        ));

        DB::table('order_timing')->insert(array(
           
            ));

        DB::table('order_delivery')->insert(array(
             array('id' => '1','created_at' => NULL,'updated_at' => NULL,'order_id' => '1','delivery_type' => 'company','delivery_address' => '1','driver_id' => '1','delivery_commission' => NULL),
          array('id' => '2','created_at' => NULL,'updated_at' => NULL,'order_id' => '2','delivery_type' => 'company','delivery_address' => '1','driver_id' => '1','delivery_commission' => NULL),
          array('id' => '3','created_at' => NULL,'updated_at' => NULL,'order_id' => '3','delivery_type' => 'company','delivery_address' => '1','driver_id' => '1','delivery_commission' => NULL),
          array('id' => '4','created_at' => NULL,'updated_at' => NULL,'order_id' => '4','delivery_type' => 'company','delivery_address' => '1','driver_id' => '1','delivery_commission' => NULL),
          array('id' => '5','created_at' => NULL,'updated_at' => NULL,'order_id' => '5','delivery_type' => 'company','delivery_address' => '1','driver_id' => '1','delivery_commission' => NULL),
          array('id' => '6','created_at' => NULL,'updated_at' => NULL,'order_id' => '6','delivery_type' => 'company','delivery_address' => '1','driver_id' => '1','delivery_commission' => NULL),
          array('id' => '7','created_at' => NULL,'updated_at' => NULL,'order_id' => '7','delivery_type' => 'company','delivery_address' => '1','driver_id' => '1','delivery_commission' => NULL),
          array('id' => '8','created_at' => NULL,'updated_at' => NULL,'order_id' => '8','delivery_type' => 'company','delivery_address' => '1','driver_id' => '1','delivery_commission' => NULL),
          array('id' => '9','created_at' => NULL,'updated_at' => NULL,'order_id' => '9','delivery_type' => 'company','delivery_address' => '1','driver_id' => '1','delivery_commission' => NULL),
          array('id' => '10','created_at' => NULL,'updated_at' => NULL,'order_id' => '10','delivery_type' => 'company','delivery_address' => '1','driver_id' => '1','delivery_commission' => NULL),
          array('id' => '11','created_at' => NULL,'updated_at' => NULL,'order_id' => '11','delivery_type' => 'company','delivery_address' => '1','driver_id' => '1','delivery_commission' => NULL),
          array('id' => '12','created_at' => NULL,'updated_at' => NULL,'order_id' => '12','delivery_type' => 'company','delivery_address' => '1','driver_id' => '1','delivery_commission' => NULL),
          array('id' => '13','created_at' => NULL,'updated_at' => NULL,'order_id' => '13','delivery_type' => 'company','delivery_address' => '1','driver_id' => '1','delivery_commission' => NULL),
          array('id' => '14','created_at' => NULL,'updated_at' => NULL,'order_id' => '14','delivery_type' => 'company','delivery_address' => '1','driver_id' => '1','delivery_commission' => NULL),
          array('id' => '15','created_at' => NULL,'updated_at' => NULL,'order_id' => '15','delivery_type' => 'company','delivery_address' => '1','driver_id' => '1','delivery_commission' => NULL),
          array('id' => '16','created_at' => NULL,'updated_at' => NULL,'order_id' => '16','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '17','created_at' => NULL,'updated_at' => NULL,'order_id' => '17','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '18','created_at' => NULL,'updated_at' => NULL,'order_id' => '18','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '19','created_at' => NULL,'updated_at' => NULL,'order_id' => '19','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '20','created_at' => NULL,'updated_at' => NULL,'order_id' => '20','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '21','created_at' => NULL,'updated_at' => NULL,'order_id' => '21','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '22','created_at' => NULL,'updated_at' => NULL,'order_id' => '22','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '23','created_at' => NULL,'updated_at' => NULL,'order_id' => '23','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '24','created_at' => NULL,'updated_at' => NULL,'order_id' => '24','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '25','created_at' => NULL,'updated_at' => NULL,'order_id' => '25','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '26','created_at' => NULL,'updated_at' => NULL,'order_id' => '26','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '27','created_at' => NULL,'updated_at' => NULL,'order_id' => '27','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '28','created_at' => NULL,'updated_at' => NULL,'order_id' => '28','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '29','created_at' => NULL,'updated_at' => NULL,'order_id' => '29','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '30','created_at' => NULL,'updated_at' => NULL,'order_id' => '30','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '31','created_at' => NULL,'updated_at' => NULL,'order_id' => '31','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '32','created_at' => NULL,'updated_at' => NULL,'order_id' => '32','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '33','created_at' => NULL,'updated_at' => NULL,'order_id' => '33','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '34','created_at' => NULL,'updated_at' => NULL,'order_id' => '34','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '35','created_at' => NULL,'updated_at' => NULL,'order_id' => '35','delivery_type' => 'company','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '36','created_at' => NULL,'updated_at' => NULL,'order_id' => '36','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '37','created_at' => NULL,'updated_at' => NULL,'order_id' => '37','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '38','created_at' => NULL,'updated_at' => NULL,'order_id' => '38','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '39','created_at' => NULL,'updated_at' => NULL,'order_id' => '39','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '40','created_at' => NULL,'updated_at' => NULL,'order_id' => '40','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '41','created_at' => NULL,'updated_at' => NULL,'order_id' => '41','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '42','created_at' => NULL,'updated_at' => NULL,'order_id' => '42','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '43','created_at' => NULL,'updated_at' => NULL,'order_id' => '43','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '44','created_at' => NULL,'updated_at' => NULL,'order_id' => '44','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '45','created_at' => NULL,'updated_at' => NULL,'order_id' => '45','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '46','created_at' => NULL,'updated_at' => NULL,'order_id' => '46','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '47','created_at' => NULL,'updated_at' => NULL,'order_id' => '47','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '48','created_at' => NULL,'updated_at' => NULL,'order_id' => '48','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '49','created_at' => NULL,'updated_at' => NULL,'order_id' => '49','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '50','created_at' => NULL,'updated_at' => NULL,'order_id' => '50','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '51','created_at' => NULL,'updated_at' => NULL,'order_id' => '51','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '52','created_at' => NULL,'updated_at' => NULL,'order_id' => '52','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '53','created_at' => NULL,'updated_at' => NULL,'order_id' => '53','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '54','created_at' => NULL,'updated_at' => NULL,'order_id' => '54','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL),
          array('id' => '55','created_at' => NULL,'updated_at' => NULL,'order_id' => '55','delivery_type' => 'own','delivery_address' => '1','driver_id' => NULL,'delivery_commission' => NULL)
                          
        ));

        DB::table('drivers')->insert(array(
            array('id' => '1','created_at' => '2021-03-11 05:17:44','updated_at' => '2021-03-11 05:17:44','title' => 'Driver','user_id' => '3','contact' => '45854654','status' => 'free','token' => NULL),
            array('id' => '2','created_at' => '2021-03-11 05:18:32','updated_at' => '2021-03-11 05:18:32','title' => 'Paik Motor1','user_id' => '6','contact' => '45854654','status' => 'free','token' => NULL)          
        ));
        DB::table('settings')->insert(array(
            array('id' => '1','key' => 'payment_range_in_days','value' => '3')
        ));

        DB::table('favorited_restaurants')->insert(array(
            array('id' => '1','created_at' => '2021-04-22 11:19:34','updated_at' => '2021-04-22 11:19:34','customer_id' => '7','branch_id' => '1'),
            array('id' => '2','created_at' => '2021-04-22 11:19:34','updated_at' => '2021-04-22 11:19:34','customer_id' => '7','branch_id' => '2')
        ));

        // \App\Models\User::factory(10)->create();
    }
}
